app/assets/forms.py
# -*- coding: utf-8 -*-

app/assets/__init__.py
from flask import Blueprint

assets = Blueprint('assets',__name__)
from . import views

app/assets/views.py
# -*- coding: utf-8 -*-
from flask import render_template, session, redirect, url_for, current_app, flash,abort,request,send_from_directory,g,_app_ctx_stack
from . import assets
from flask_login import login_user, logout_user, login_required,current_user
from .. import login_manager
from time import strftime,strptime,mktime,localtime,time
from ..decorators import admin_required
import json,string,pymysql,re
from random import choice
from .. import get_db,prpcrypt

import sys
reload(sys)
sys.setdefaultencoding('utf8')


@assets.before_request
def before_request():
	g.user = current_user
	# g.connect_db = get_db()


'''
资产管理 -- 资产列表
'''

# 资产信息列表 - 页面视图
@assets.route('/asset_list', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_list():
	app = "资产管理"
	action = "资产列表"
	return render_template('assets/asset_list.html',app=app,action=action)

# 资产信息列表 - 新增资产视图
@assets.route('/asset_create', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_create():
	app = "资产管理"
	action = "新增资产"
	if request.method == 'POST':
		con = get_db()
		cursor = con.cursor()

		assets_host_ip = request.form['assets_host_ip']
		assets_host_dbtype = request.form['assets_host_dbtype']
		assets_host_dbaccount = request.form['assets_host_dbaccount']
		assets_host_dbpasswd = request.form['assets_host_dbpasswd']
		assets_host_dbport = request.form['assets_host_dbport']
		assets_host_note = request.form.get('assets_host_note')
		assets_host_status = request.form.get('assets_host_status')
		currentTime = strftime("%Y-%m-%d %H:%M:%S")
		currentTimeStamp = int(mktime(strptime(currentTime,"%Y-%m-%d %H:%M:%S")))
		if assets_host_status:
			assets_host_status = 0
		else:
			assets_host_status = 1
		pc = prpcrypt(str(currentTimeStamp))
		pwhash = pc.encrypt(assets_host_dbpasswd)
		insert_assetinfo_sql = "INSERT INTO dbadmin_assets_hosts(ipaddress,dbtype,db_account,db_password,db_port,status,createTime,updateTime,note) VALUES('{ipaddress}',{dbtype},'{db_account}','{db_password}',{db_port},{status},'{createTime}','{updateTime}','{note}');".format(
			ipaddress=assets_host_ip, dbtype=int(assets_host_dbtype), db_account=assets_host_dbaccount, db_password=pwhash, db_port=assets_host_dbport, status=assets_host_status, createTime=currentTime, updateTime=currentTime, note=assets_host_note)
		try:
			record_list = [[u'IP地址','',assets_host_ip],[u'数据库类型','',int(assets_host_dbtype)],[u'DB账号','',assets_host_dbaccount],[u'DB端口','',assets_host_dbport],[u'状态','',assets_host_status],[u'备注','',assets_host_note]]
			cursor.execute(insert_assetinfo_sql)
			new_id = cursor.lastrowid
			insert_assetinfo_record_sql = "INSERT INTO dbadmin_assets_hosts_record(hostid,username,status,createTime,content) VALUES ('{hostid}','{username}',{status},'{createTime}',\"{content}\");".format(
									hostid=int(new_id),username=g.user.username,status=0,createTime=currentTime,content=record_list)
			cursor.execute(insert_assetinfo_record_sql)
			cursor.execute("COMMIT;")
		except Exception as e:
			print(e)
		return redirect(url_for('assets.asset_list'))

	return render_template('assets/asset_create.html',app=app,action=action)


# 资产信息列表 - ajax视图
@assets.route('/asset_list_ajax', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_list_ajax():
	# 获取ajax中传递的request的data值
	page_dict = {'page_content': None, 'page_count': None,'per_page':None}
	data = request.get_json()

	# 初始化对dbadmin系统后台数据库的访问
	con = get_db()
	cursor = con.cursor()

	# 对非空的条件进行SQL语句拼接
	page = int(data['page'])
	condition = 'WHERE 1=1'
	if data['assetlist_keyword']:
		condition += " AND A.ipaddress like '%{ip}%'".format(ip=data['assetlist_keyword'].strip())
	if data['assetlist_dbtype']:
		condition += " AND A.dbtype = '{dbtype}'".format(dbtype=int(data['assetlist_dbtype']))
	if data['assetlist_status']:
		condition += " AND A.status = '{status}'".format(status=int(data['assetlist_status']))

	# 获取总数据行数
	assetlist_count_sql = "SELECT COUNT(A.id) FROM dbadmin_assets_hosts A  {condition};".format(condition=condition)
	cursor.execute(assetlist_count_sql)
	assetscount_result = cursor.fetchall()
	page_dict['page_count'] = assetscount_result[0][0]
	if int(data['asset_data_length']) != 100:
		page_dict['per_page'] = int(data['asset_data_length'])
		per_page = int(data['asset_data_length'])
	else:
		page_dict['per_page'] = int(assetscount_result[0][0])
		per_page = int(assetscount_result[0][0])

	# 获取首页展示的数据
	assetlist_select_sql = "SELECT A.id,A.ipaddress,A.dbtype,A.db_account,A.db_port,A.status,A.createTime FROM dbadmin_assets_hosts A  {condition} ORDER BY A.id DESC LIMIT {start},{per_page};".format(
		start=(page - 1) * per_page, condition=condition, per_page=per_page)
	cursor.execute(assetlist_select_sql)
	assetlist_result = cursor.fetchall()

	page_cont_str = ''
	for i in assetlist_result:

		# 主机状态类型
		if int(i[5]) == 0:
			asset_status = '<span class="label label-primary" style="font-size:12px;">已激活</span>'
			op_type = '<a class="btn btn-xs btn-danger" href="/assets/asset_toggle/{id}/{status}">禁用</a>'.format(id=int(i[0]),status=int(i[5]))
		else:
			asset_status = '<span class="label label-warning" style="font-size:12px;">未激活</span>'
			op_type = '<a class="btn btn-xs btn-primary" href="/assets/asset_toggle/{id}/{status}">启用</a>'.format(id=int(i[0]),status=int(i[5]))

		# 数据库类型
		if int(i[2]) == 0:
			assets_host_dbtype = 'MySQL'
		elif int(i[2]) == 1:
			assets_host_dbtype = 'ORACLE'
		elif int(i[2]) == 2:
			assets_host_dbtype = 'Redis'
		elif int(i[2]) == 3:
			assets_host_dbtype = 'MongoDB'
		else:
			assets_host_dbtype = '其他'

		page_cont_str += '''
					<tr class="gradeX">
						<td class="text-center">
							<input type="checkbox" name="checked" value="{id}" class="ipt_check">
						</td>
						<td class="text-center">{id}</td>
						<td class="text-center"><a href="/assets/asset_detail/{id}">{assets_host_ip}</a></td>
						<td class="text-center" title=""><span class="label label-primary" style="font-size:12px;">{assets_host_dbtype}</span></td>
						<td class="text-center">{assets_host_dbaccount}</td>
						<td class="text-center" >{assets_host_dbport}</td>
						<td class="text-center">{assets_host_status}</td>
						<td class="text-center">{assets_host_ctime}</td>
						<td class="text-center">
							<a href="/assets/asset_edit/{id}" class="btn btn-xs btn-info">编辑</a>
							{op_type}
							<a onClick="return confirm('确认要删除 {assets_host_ip} 这个主机？')" href="/assets/asset_delete/{id}" class="btn btn-xs btn-danger del">删除</a>
						</td>
					</tr>
					'''.format(id=int(i[0]),assets_host_ip=i[1],assets_host_dbtype=assets_host_dbtype,assets_host_dbaccount=i[3],assets_host_dbport=i[4],question=i[5],assets_host_status=asset_status,assets_host_ctime=i[6],op_type=op_type)
	page_dict['page_content'] = page_cont_str

	return json.dumps(page_dict)

# 资产信息列表 - 资产详情视图
@assets.route('/asset_detail/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_detail(id):

	app = "资产管理"
	action = "资产详情"
	con = get_db()
	cursor = con.cursor()
	get_asset_detail_sql = "SELECT A.id,A.ipaddress,A.dbtype,A.db_account,A.db_port,A.status,A.createTime,A.note FROM dbadmin_assets_hosts A WHERE A.id = {id};".format(id=id)
	cursor.execute(get_asset_detail_sql)
	asset_detail_result = cursor.fetchall()

	get_asset_db_sql = "SELECT name,status,createTime,tables_nums FROM dbadmin_assets_mysqldb WHERE hostid={hostid};".format(hostid=id)
	cursor.execute(get_asset_db_sql)
	asset_db_result = cursor.fetchall()

	return render_template('assets/asset_detail.html',app=app,action=action,asset_detail_result=asset_detail_result,asset_db_result=asset_db_result)

# 资产信息列表 - 启用禁用功能视图
@assets.route('/asset_toggle/<int:id>/<int:status>', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_toggle(id,status):
	con = get_db()
	cursor = con.cursor()
	if status == 1:
		asset_status = 0
	else:
		asset_status = 1
	update_asset_status_sql = "UPDATE dbadmin_assets_hosts SET status={status} WHERE id={id};".format(status=asset_status,id=id)
	try:
		cursor.execute(update_asset_status_sql)
		cursor.execute('COMMIT;')
	except Exception as e:
		print(e)

	return redirect(url_for('assets.asset_list'))

# 资产信息列表 - 删除功能视图
@assets.route('/asset_delete/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_delete(id):
	con = get_db()
	cursor = con.cursor()
	delete_asset_sql = "DELETE FROM dbadmin_assets_hosts WHERE id='{id}';".format(id=id)
	try:
		cursor.execute(delete_asset_sql)
		cursor.execute('COMMIT;')
	except Exception as e:
		print(e)

	return redirect(url_for('assets.asset_list'))

# 资产信息列表 - 编辑功能视图
@assets.route('/asset_edit/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def asset_edit(id):
	con = get_db()
	cursor = con.cursor()

	get_assetinfo_sql = "SELECT A.ipaddress,A.dbtype,A.db_account,A.db_password,A.db_port,A.note,A.status,A.createTime FROM dbadmin_assets_hosts A  WHERE A.id='{id}';".format(id=id)
	cursor.execute(get_assetinfo_sql)
	assetinfo_result = cursor.fetchall()
	assetinfo_list = list(assetinfo_result[0])
	createTimeStamp = str(int(mktime(strptime(assetinfo_list[7],"%Y-%m-%d %H:%M:%S"))))
	pc = prpcrypt(createTimeStamp)
	assetinfo_list[3] = pc.decrypt(assetinfo_list[3])
	app = "资产管理"
	action = "编辑资产"
	if request.method == 'POST':
		assets_host_ip = request.form['assets_host_ip']
		assets_host_dbtype = request.form['assets_host_dbtype']
		assets_host_dbaccount = request.form['assets_host_dbaccount']
		assets_host_dbpasswd = request.form['assets_host_dbpasswd']
		assets_host_dbport = request.form['assets_host_dbport']
		assets_host_note = request.form.get('assets_host_note')
		assets_host_status = request.form.get('assets_host_status')
		if assets_host_status:
			assets_host_status = 0
		else:
			assets_host_status = 1
		pwhash = pc.encrypt(assets_host_dbpasswd)
		currentTime = strftime("%Y-%m-%d %H:%M:%S")

app/templates/assets/asset_create.html
{% extends 'base.html' %}
{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-7">
            <div class="ibox float-e-margins" id="all">

                <div class="ibox-title">
                    <h5> 新建资产</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content" style="background-color: #ffffff">
                    <form class="form-horizontal" role="form" method="post" action="" >
                        <div class="form-group">
                            <label class="col-sm-3 control-label">主机IP地址<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" value="" id="assets_host_ip" name="assets_host_ip" placeholder="IP地址" required="" pattern="^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$" oninvalid="setCustomValidity('不符合IP地址的规则');" oninput="setCustomValidity('');">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库类型<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <select class="form-control" name="assets_host_dbtype" id="assets_host_dbtype" required>
                                    <option value="0">MySQL</option>
                                    <option value="1">ORACLE</option>
                                    <option value="2">Redis</option>
                                    <option value="3">MongoDB</option>
                                    <option value="99">其他</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库账号<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" value="" name="assets_host_dbaccount" placeholder="英文字符" required="" oninvalid="setCustomValidity('数据库账号必须填写!');" oninput="setCustomValidity('');">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库密码<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <input type="password" class="form-control input-xlarge" id="assets_host_dbpasswd" name="assets_host_dbpasswd" placeholder=""   value="" required oninvalid="setCustomValidity('密码必须填写!');" oninput="setCustomValidity('');"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库端口<span style="color: red">*</span></label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" value="" name="assets_host_dbport" placeholder="" required="" oninvalid="setCustomValidity('数据库端口必须填写!');" oninput="setCustomValidity('');" onkeypress="return event.keyCode>=48&&event.keyCode<=57">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">备注(选填)</label>
                            <div class="col-sm-8">
                                <textarea id="assets_host_note" name="assets_host_note" class="form-control" placeholder="限150字以内" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-group" >
                             <label class="col-sm-3 control-label">已启用</label>
                             <div class="col-sm-5">
                                    <input type="checkbox" id="assets_host_status" name="assets_host_status" value="0" class="checkbox-radio" checked="checked" style="margin: 10px 0 0;">
                             </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6 col-sm-offset-3">
                                <button id="assets_host_submit" class="btn btn-primary" type="submit">新建</button>
                                <a class="btn btn-info" href="{{ url_for('assets.asset_list') }}">返回</a>
                                <a style="cursor:default;color: red">* 为必填项</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<script>-->
<!--function validateIP(ip) {-->
    <!--var strRegex=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;-->
    <!--if (strRegex.test(ip)) {-->
        <!--return true;-->
    <!--}-->
    <!--else {-->
        <!--$('#assets_host_ip').val('');-->
        <!--return false;-->
    <!--}-->
<!--}-->
<!--</script>-->


{% endblock %}

app/templates/assets/asset_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-7">
            <div class="ibox float-e-margins" id="all">

                <div class="ibox-title">
                    <h5> 编辑资产</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content" style="background-color: #ffffff">
                    <form class="form-horizontal" role="form" method="post" action="" >
                        <div class="form-group">
                            <label class="col-sm-3 control-label">主机IP地址<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" value="{{ assetinfo_result[0] }}" id="assets_host_ip" name="assets_host_ip" placeholder="IP地址" required="" pattern="^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$" oninvalid="setCustomValidity('不符合IP地址的规则');" oninput="setCustomValidity('');">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库类型<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <select class="form-control" name="assets_host_dbtype" id="assets_host_dbtype" required>
                                    <option value="0">MySQL</option>
                                    <option value="1">ORACLE</option>
                                    <option value="2">Redis</option>
                                    <option value="3">MongoDB</option>
                                    <option value="99">其他</option>
                                    {% if assetinfo_result[1] == 0 %}
                                        <option value="0" selected="selected">MySQL</option>
                                        <option value="1">ORACLE</option>
                                        <option value="2">Redis</option>
                                        <option value="3">MongoDB</option>
                                        <option value="99">其他</option>
                                    {% elif assetinfo_result[1] == 1 %}
                                        <option value="0">MySQL</option>
                                        <option value="1"  selected="selected">ORACLE</option>
                                        <option value="2">Redis</option>
                                        <option value="3">MongoDB</option>
                                        <option value="99">其他</option>
                                    {% elif assetinfo_result[1] == 2 %}
                                        <option value="0">MySQL</option>
                                        <option value="1">ORACLE</option>
                                        <option value="2"  selected="selected">Redis</option>
                                        <option value="3">MongoDB</option>
                                        <option value="99">其他</option>
                                    {% elif assetinfo_result[1] == 3 %}
                                        <option value="0">MySQL</option>
                                        <option value="1">ORACLE</option>
                                        <option value="2">Redis</option>
                                        <option value="3"  selected="selected">MongoDB</option>
                                        <option value="99">其他</option>
                                    {% else %}
                                        <option value="0">MySQL</option>
                                        <option value="1">ORACLE</option>
                                        <option value="2">Redis</option>
                                        <option value="3">MongoDB</option>
                                        <option value="99" selected="selected">其他</option>
                                    {% endif %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库账号<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" value="{{ assetinfo_result[2] }}" name="assets_host_dbaccount" placeholder="英文字符" required="" oninvalid="setCustomValidity('数据库账号必须填写!');" oninput="setCustomValidity('');">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库密码<span style="color: red">*</span></label>
                            <div class="col-sm-5">
                                <input type="password" class="form-control input-xlarge" id="assets_host_dbpasswd" name="assets_host_dbpasswd" placeholder=""   value="{{ assetinfo_result[3] }}" required oninvalid="setCustomValidity('密码必须填写!');" oninput="setCustomValidity('');"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">数据库端口<span style="color: red">*</span></label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" value="{{ assetinfo_result[4] }}" name="assets_host_dbport" placeholder="" required="" oninvalid="setCustomValidity('数据库端口必须填写!');" oninput="setCustomValidity('');" onkeypress="return event.keyCode>=48&&event.keyCode<=57">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">备注(选填)</label>
                            <div class="col-sm-8">
                                <textarea id="assets_host_note" name="assets_host_note" class="form-control" placeholder="限150字以内" rows="3">{{ assetinfo_result[5] }}</textarea>
                            </div>
                        </div>
                        <div class="form-group" >
                             <label class="col-sm-3 control-label">已启用</label>
                             <div class="col-sm-5">
                                 {% if assetinfo_result[6] == 0 %}
                                    <input type="checkbox"  name="assets_host_status" value="0" class="checkbox-radio" checked="checked" style="margin: 10px 0 0;">
                                 {% else %}
                                    <input type="checkbox"  name="assets_host_status" value="0" class="checkbox-radio"  style="margin: 10px 0 0;">
                                 {% endif %}
                             </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6 col-sm-offset-3">
                                <button id="assets_host_submit" class="btn btn-primary" type="submit">完成编辑</button>
                                <a class="btn btn-info" href="{{ url_for('assets.asset_list') }}">返回</a>
                                <a style="cursor:default;color: red">* 为必填项</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<script>-->
<!--function validateIP(ip) {-->
    <!--var strRegex=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;-->
    <!--if (strRegex.test(ip)) {-->
        <!--return true;-->
    <!--}-->
    <!--else {-->
        <!--$('#assets_host_ip').val('');-->
        <!--return false;-->
    <!--}-->
<!--}-->
<!--</script>-->


{% endblock %}

app/templates/assets/asset_list.html
{% extends '_base_list.html' %}
{% block table_container %}
<div class="" id="content_start">
    {% block content_left_head %} {% endblock %}
    {% block table_search %}
    <form id="search_form" method="get" action="" class="form-inline">
        {% block search_form %}
        <div class="col-sm-1" style="padding-left:0;padding-bottom: 4px">
            <a href="{{ url_for('assets.asset_create') }}" class="btn btn-sm btn-primary"> 新建主机 </a>
        </div>

        <div class="col-sm-7 pull-right" style="padding-left:0;padding-bottom: 4px;padding-right:0;">
            <div class="pull-right">
                <div class="input-group">
                    <select class="form-control input-sm m-b" style="width: auto;padding: 2px;" id="asset_data_length">
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="30">30</option>
                        <option value="100">ALL</option>
                    </select>
                </div>
                <div class="input-group">
                    <select class="form-control input-sm m-b" style="width: auto;padding: 2px;" id="assets_host_dbtype">
                        <option value>数据库类型</option>
                        <option value="0">MySQL</option>
                        <option value="1">ORACLE</option>
                        <option value="2">Redis</option>
                        <option value="3">MongoDB</option>
                        <option value="99">其他</option>
                    </select>
                </div>
                <div class="input-group">
                    <select class="form-control input-sm m-b" style="width: auto;padding: 2px;" id="assets_host_status">
                        <option value>主机状态</option>
                        <option value="0">已激活</option>
                        <option value="1">未激活</option>
                    </select>
                </div>
                <div class="input-group">
                    <input type="text" class="form-control input-sm m-b" id="assetlist_keyword" name="assetlist_keyword" placeholder="IP地址" value="">
                </div>
                <div class="input-group">
                    <div class="input-group-btn">
                        <a id='search_btn' type="submit" class="btn btn-sm btn-primary">
                            搜索
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </form>
    {% endblock %}
</div>

<table class="table table-striped table-bordered table-hover dataTable no-footer" id="asset_list_table" >
    <thead>
        <tr>
            <th class="text-center">
                <input id="" type="checkbox" class="ipt_check_all">
            </th>
            <th class="text-center">主机ID</th>
            <th class="text-center">IP地址</th>
            <th class="text-center">数据库类型</th>
            <th class="text-center">数据库账号</th>
            <th class="text-center">数据库端口</th>
            <th class="text-center">主机状态</th>
            <th class="text-center">创建时间</th>
            <th class="text-center">操作</th>
        </tr>
    </thead>
    <tbody id="assetlist_dynamic">
    </tbody>
</table>
<div style='text-align:center;' id="assetlist_notfound"></div>

<div class="row m-t">
    <div class="col-md-4">
        <div class="form-inline">
            <div class="input-group">
                <select class="form-control m-b" style="width: auto;font-size:12px;padding: 2px;" id="slct_bulk_update">
                    <option value="active">批量启用</option>
                    <option value="deactive">批量禁用</option>
                    <option value="delete">批量删除</option>
                </select>
            </div>
            <div class="input-group">
                <div class="input-group-btn">
                    <a id='btn_bulk_update' style="height: 32px;" type="submit" class="btn btn-sm btn-primary">
                        提交
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div id="example_assetlist" style="text-align: center" class="pull-right">
            <div id="assetlist_notes" style="text-align: center;padding-top: 8px;padding-right: 6px;" class="pull-left"></div>
            <ul id="assetlist_pageLimit" style="margin: 0 0;"></ul>
        </div>
    </div>
</div>


<!--操作状态返回警告框 modal-->
<div class="row">
    <div class="modal " id="bulkResultModal" tabindex="-1" role="dialog" aria-labelledby="bulkResultLabel" aria-hidden="true" data-backdrop="static" style="top:140px">
        <div class="modal-dialog" style="padding: 20px 180px">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="bulkResultLabel">
                        操作结果
                    </h4>
                </div>
                <div class="modal-header" style="text-align: center;">
                    <div id="bulkResultInfo"></div>
                </div>
                <div class="modal-footer" style="text-align: center;padding: 0">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block content_bottom_left %}
<script src="{{ url_for('static', filename='js/bootstrap-paginator.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/assets/asset_list.js') }}"></script>
{% endblock %}